// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: srcjflexcup/lexer.flex

/* JFlex example: part of Java language lexer specification */
package jflex;
import java_cup.runtime.*;import java.util.HashMap;

/**
* This class is a simple example lexer.
*/

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int COMMENT = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\41\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u0100"+
    "\1\u3a00\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100"+
    "\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800\1\u4900"+
    "\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u1f00\1\u4e00\1\u4f00\1\u5000"+
    "\1\u5100\3\u0100\1\u5200\1\u5300\1\u5400\12\u1f00\4\u0100\1\u5500"+
    "\17\u1f00\2\u0100\1\u5600\41\u1f00\2\u0100\1\u5700\1\u5800\2\u1f00"+
    "\1\u5900\1\u5a00\27\u0100\1\u5b00\4\u0100\1\u5c00\1\u5d00\42\u1f00"+
    "\1\u0100\1\u5e00\1\u5f00\11\u1f00\1\u6000\24\u1f00\1\u6100\1\u6200"+
    "\1\u1f00\1\u6300\1\u6400\1\u6500\1\u6600\2\u1f00\1\u6700\5\u1f00"+
    "\1\u6800\1\u6900\1\u6a00\5\u1f00\1\u6b00\1\u6c00\2\u1f00\1\u6d00"+
    "\1\u1f00\1\u6e00\14\u1f00\1\u6f00\4\u1f00\246\u0100\1\u7000\20\u0100"+
    "\1\u7100\1\u7200\25\u0100\1\u7300\34\u0100\1\u7400\14\u1f00\2\u0100"+
    "\1\u7500\5\u1f00\23\u0100\1\u7600\u0aec\u1f00\1\u7700\1\u7800\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\16\0\4\3"+
    "\1\1\1\3\1\5\1\3\1\6\3\3\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\11\20"+
    "\1\3\1\21\1\22\1\23\1\24\2\3\4\25\1\26"+
    "\25\25\4\3\1\25\1\3\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\25\1\35\1\36\2\25\1\37\1\40"+
    "\1\41\1\42\1\43\1\25\1\44\1\45\1\46\1\47"+
    "\1\50\1\51\3\25\1\52\1\3\1\53\1\3\41\0"+
    "\2\3\4\25\4\3\1\25\2\3\1\0\7\3\1\25"+
    "\4\3\1\25\5\3\27\25\1\3\37\25\1\3\u01ca\25"+
    "\4\3\14\25\16\3\5\25\7\3\1\25\1\3\1\25"+
    "\21\3\160\0\5\25\1\3\2\25\2\3\4\25\1\3"+
    "\1\25\6\3\1\25\1\3\3\25\1\3\1\25\1\3"+
    "\24\25\1\3\123\25\1\3\213\25\1\3\5\0\2\3"+
    "\246\25\1\3\46\25\2\3\1\25\6\3\51\25\6\3"+
    "\1\25\1\3\55\0\1\3\1\0\1\3\2\0\1\3"+
    "\2\0\1\3\1\0\10\3\33\25\4\3\4\25\15\3"+
    "\6\0\5\3\1\25\4\3\13\0\1\3\1\0\3\3"+
    "\53\25\37\0\4\3\2\25\1\0\143\25\1\3\1\25"+
    "\10\0\1\3\6\0\2\25\2\0\1\3\4\0\2\25"+
    "\12\0\3\25\2\3\1\25\17\3\1\0\1\25\1\0"+
    "\36\25\33\0\2\3\131\25\13\0\1\25\16\3\12\0"+
    "\41\25\11\0\2\25\4\3\1\25\2\3\1\0\30\25"+
    "\4\0\1\25\11\0\1\25\3\0\1\25\5\0\22\3"+
    "\31\25\3\0\4\3\13\25\65\3\25\25\1\3\22\25"+
    "\13\3\61\0\66\25\3\0\1\25\22\0\1\25\7\0"+
    "\12\25\2\0\2\3\12\0\1\3\20\25\3\0\1\3"+
    "\10\25\2\3\2\25\2\3\26\25\1\3\7\25\1\3"+
    "\1\25\3\3\4\25\2\3\1\0\1\25\7\0\2\3"+
    "\2\0\2\3\3\0\1\25\10\3\1\0\4\3\2\25"+
    "\1\3\3\25\2\0\2\3\12\0\4\25\7\3\2\25"+
    "\1\3\1\0\2\3\3\0\1\3\6\25\4\3\2\25"+
    "\2\3\26\25\1\3\7\25\1\3\2\25\1\3\2\25"+
    "\1\3\2\25\2\3\1\0\1\3\5\0\4\3\2\0"+
    "\2\3\3\0\3\3\1\0\7\3\4\25\1\3\1\25"+
    "\7\3\14\0\3\25\1\0\13\3\3\0\1\3\11\25"+
    "\1\3\3\25\1\3\26\25\1\3\7\25\1\3\2\25"+
    "\1\3\5\25\2\3\1\0\1\25\10\0\1\3\3\0"+
    "\1\3\3\0\2\3\1\25\17\3\2\25\2\0\2\3"+
    "\12\0\1\3\1\25\7\3\1\25\6\0\1\3\3\0"+
    "\1\3\10\25\2\3\2\25\2\3\26\25\1\3\7\25"+
    "\1\3\2\25\1\3\5\25\2\3\1\0\1\25\7\0"+
    "\2\3\2\0\2\3\3\0\7\3\3\0\4\3\2\25"+
    "\1\3\3\25\2\0\2\3\12\0\1\3\1\25\20\3"+
    "\1\0\1\25\1\3\6\25\3\3\3\25\1\3\4\25"+
    "\3\3\2\25\1\3\1\25\1\3\2\25\3\3\2\25"+
    "\3\3\3\25\3\3\14\25\4\3\5\0\3\3\3\0"+
    "\1\3\4\0\2\3\1\25\6\3\1\0\16\3\12\0"+
    "\11\3\1\25\6\3\5\0\10\25\1\3\3\25\1\3"+
    "\27\25\1\3\20\25\3\3\1\25\7\0\1\3\3\0"+
    "\1\3\4\0\7\3\2\0\1\3\3\25\5\3\2\25"+
    "\2\0\2\3\12\0\20\3\1\25\3\0\1\3\10\25"+
    "\1\3\3\25\1\3\27\25\1\3\12\25\1\3\5\25"+
    "\2\3\1\0\1\25\7\0\1\3\3\0\1\3\4\0"+
    "\7\3\2\0\7\3\1\25\1\3\2\25\2\0\2\3"+
    "\12\0\1\3\2\25\15\3\4\0\11\25\1\3\3\25"+
    "\1\3\51\25\2\0\1\25\7\0\1\3\3\0\1\3"+
    "\4\0\1\25\5\3\3\25\1\0\7\3\3\25\2\0"+
    "\2\3\12\0\12\3\6\25\1\3\3\0\1\3\22\25"+
    "\3\3\30\25\1\3\11\25\1\3\1\25\2\3\7\25"+
    "\3\3\1\0\4\3\6\0\1\3\1\0\1\3\10\0"+
    "\6\3\12\0\2\3\2\0\15\3\60\25\1\0\2\25"+
    "\7\0\4\3\10\25\10\0\1\3\12\0\47\3\2\25"+
    "\1\3\1\25\1\3\5\25\1\3\30\25\1\3\1\25"+
    "\1\3\12\25\1\0\2\25\11\0\1\25\2\3\5\25"+
    "\1\3\1\25\1\3\6\0\2\3\12\0\2\3\4\25"+
    "\40\3\1\25\27\3\2\0\6\3\12\0\13\3\1\0"+
    "\1\3\1\0\1\3\1\0\4\3\2\0\10\25\1\3"+
    "\44\25\4\3\24\0\1\3\2\0\5\25\13\0\1\3"+
    "\44\0\11\3\1\0\71\3\53\25\24\0\1\25\12\0"+
    "\6\3\6\25\4\0\4\25\3\0\1\25\3\0\2\25"+
    "\7\0\3\25\4\0\15\25\14\0\1\25\17\0\2\3"+
    "\46\25\1\3\1\25\5\3\1\25\2\3\53\25\1\3"+
    "\115\25\1\3\4\25\2\3\7\25\1\3\1\25\1\3"+
    "\4\25\2\3\51\25\1\3\4\25\2\3\41\25\1\3"+
    "\4\25\2\3\7\25\1\3\1\25\1\3\4\25\2\3"+
    "\17\25\1\3\71\25\1\3\4\25\2\3\103\25\2\3"+
    "\3\0\40\3\20\25\20\3\126\25\2\3\6\25\3\3"+
    "\u016c\25\2\3\21\25\1\3\32\25\5\3\113\25\3\3"+
    "\13\25\7\3\15\25\1\3\4\25\3\0\13\3\22\25"+
    "\3\0\13\3\22\25\2\0\14\3\15\25\1\3\3\25"+
    "\1\3\2\0\14\3\64\25\40\0\3\3\1\25\3\3"+
    "\2\25\1\0\2\3\12\0\41\3\4\0\1\3\12\0"+
    "\6\3\131\25\7\3\5\25\2\0\42\25\1\0\1\25"+
    "\5\3\106\25\12\3\37\25\1\3\14\0\4\3\14\0"+
    "\12\3\12\0\36\25\2\3\5\25\13\3\54\25\4\3"+
    "\32\25\6\3\12\0\46\3\27\25\5\0\4\3\65\25"+
    "\12\0\1\3\35\0\2\3\13\0\6\3\12\0\15\3"+
    "\1\25\10\3\16\0\1\3\2\0\77\3\5\0\57\25"+
    "\21\0\7\25\4\3\12\0\21\3\11\0\14\3\3\0"+
    "\36\25\15\0\2\25\12\0\54\25\16\0\14\3\44\25"+
    "\24\0\10\3\12\0\3\3\3\25\12\0\44\25\2\3"+
    "\11\25\7\3\53\25\2\3\3\25\20\3\3\0\1\3"+
    "\25\0\4\25\1\0\6\25\1\0\2\25\3\0\1\25"+
    "\5\3\300\25\72\0\1\3\5\0\26\25\2\3\6\25"+
    "\2\3\46\25\2\3\6\25\2\3\10\25\1\3\1\25"+
    "\1\3\1\25\1\3\1\25\1\3\37\25\2\3\65\25"+
    "\1\3\7\25\1\3\1\25\3\3\3\25\1\3\7\25"+
    "\3\3\4\25\2\3\6\25\4\3\15\25\5\3\3\25"+
    "\1\3\7\25\16\3\5\0\32\3\5\0\20\3\2\25"+
    "\23\3\1\25\13\3\5\0\1\3\12\0\1\3\1\25"+
    "\15\3\1\25\20\3\15\25\3\3\40\25\20\3\15\0"+
    "\4\3\1\0\3\3\14\0\21\3\1\25\4\3\1\25"+
    "\2\3\12\25\1\3\1\25\3\3\5\25\6\3\1\25"+
    "\1\3\1\25\1\3\1\25\1\3\4\25\1\3\13\25"+
    "\2\3\4\25\5\3\5\25\4\3\1\25\21\3\51\25"+
    "\u0177\3\57\25\1\3\57\25\1\3\205\25\6\3\4\25"+
    "\3\0\2\25\14\3\46\25\1\3\1\25\5\3\1\25"+
    "\2\3\70\25\7\3\1\25\17\3\1\0\27\25\11\3"+
    "\7\25\1\3\7\25\1\3\7\25\1\3\7\25\1\3"+
    "\7\25\1\3\7\25\1\3\7\25\1\3\7\25\1\3"+
    "\40\0\57\3\1\25\325\3\3\25\31\3\11\25\6\0"+
    "\1\3\5\25\2\3\5\25\4\3\126\25\2\3\2\0"+
    "\2\3\3\25\1\3\132\25\1\3\4\25\5\3\53\25"+
    "\1\3\136\25\21\3\40\25\60\3\320\25\100\3\375\25"+
    "\3\3\215\25\103\3\56\25\2\3\15\25\3\3\20\25"+
    "\12\0\2\25\24\3\57\25\1\0\4\3\12\0\1\3"+
    "\37\25\2\0\120\25\2\0\45\3\11\25\2\3\147\25"+
    "\2\3\65\25\2\3\11\25\52\3\15\25\1\0\3\25"+
    "\1\0\4\25\1\0\27\25\5\0\4\3\1\0\13\3"+
    "\1\25\7\3\64\25\14\3\2\0\62\25\22\0\12\3"+
    "\12\0\6\3\22\0\6\25\3\3\1\25\1\3\2\25"+
    "\13\0\34\25\10\0\2\3\27\25\15\0\14\3\35\25"+
    "\3\3\4\0\57\25\16\0\16\3\1\25\12\0\6\3"+
    "\5\25\1\0\12\25\12\0\5\25\1\3\51\25\16\0"+
    "\11\3\3\25\1\0\10\25\2\0\2\3\12\0\6\3"+
    "\27\25\3\3\1\25\3\0\62\25\1\0\1\25\3\0"+
    "\2\25\2\0\5\25\2\0\1\25\1\0\1\25\30\3"+
    "\3\25\2\3\13\25\5\0\2\3\3\25\2\0\12\3"+
    "\6\25\2\3\6\25\2\3\6\25\11\3\7\25\1\3"+
    "\7\25\1\3\53\25\1\3\16\25\6\3\163\25\10\0"+
    "\1\3\2\0\2\3\12\0\6\3\244\25\14\3\27\25"+
    "\4\3\61\25\4\3\156\25\2\3\152\25\46\3\7\25"+
    "\14\3\5\25\5\3\1\25\1\0\12\25\1\3\15\25"+
    "\1\3\5\25\1\3\1\25\1\3\2\25\1\3\2\25"+
    "\1\3\154\25\41\3\153\25\22\3\100\25\2\3\66\25"+
    "\50\3\15\25\3\3\20\0\20\3\20\0\3\3\2\25"+
    "\30\3\3\25\31\3\1\25\6\3\5\25\1\3\207\25"+
    "\2\3\1\0\4\3\1\25\13\3\12\0\7\3\32\25"+
    "\4\3\1\25\1\3\32\25\13\3\131\25\3\3\6\25"+
    "\2\3\6\25\2\3\6\25\2\3\3\25\3\3\2\25"+
    "\3\3\2\25\22\3\3\0\4\3\14\25\1\3\32\25"+
    "\1\3\23\25\1\3\2\25\1\3\17\25\2\3\16\25"+
    "\42\3\173\25\105\3\65\25\210\3\1\0\202\3\35\25"+
    "\3\3\61\25\17\3\1\0\37\3\40\25\15\3\36\25"+
    "\5\3\46\25\5\0\5\3\36\25\2\3\44\25\4\3"+
    "\10\25\1\3\5\25\52\3\236\25\2\3\12\0\6\3"+
    "\44\25\4\3\44\25\4\3\50\25\10\3\64\25\234\3"+
    "\67\25\11\3\26\25\12\3\10\25\230\3\6\25\2\3"+
    "\1\25\1\3\54\25\1\3\2\25\3\3\1\25\2\3"+
    "\27\25\12\3\27\25\11\3\37\25\101\3\23\25\1\3"+
    "\2\25\12\3\26\25\12\3\32\25\106\3\70\25\6\3"+
    "\2\25\100\3\1\25\3\0\1\3\2\0\5\3\4\0"+
    "\4\25\1\3\3\25\1\3\35\25\2\3\3\0\4\3"+
    "\1\0\40\3\35\25\3\3\35\25\43\3\10\25\1\3"+
    "\34\25\2\0\31\3\66\25\12\3\26\25\12\3\23\25"+
    "\15\3\22\25\156\3\111\25\67\3\63\25\15\3\63\25"+
    "\15\3\44\25\4\0\10\3\12\0\u0146\3\52\25\1\3"+
    "\2\0\3\3\2\25\116\3\35\25\12\3\1\25\10\3"+
    "\26\25\13\0\137\3\25\25\33\3\27\25\11\3\3\0"+
    "\65\25\17\0\37\3\12\0\17\3\4\0\55\25\13\0"+
    "\2\3\1\0\17\3\1\0\2\3\31\25\7\3\12\0"+
    "\6\3\3\0\44\25\16\0\1\3\12\0\4\3\1\25"+
    "\2\0\1\25\10\3\43\25\1\0\2\3\1\25\11\3"+
    "\3\0\60\25\16\0\4\25\4\3\4\0\1\3\14\0"+
    "\1\25\1\3\1\25\43\3\22\25\1\3\31\25\14\0"+
    "\6\3\1\0\101\3\7\25\1\3\1\25\1\3\4\25"+
    "\1\3\17\25\1\3\12\25\7\3\57\25\14\0\5\3"+
    "\12\0\6\3\4\0\1\3\10\25\2\3\2\25\2\3"+
    "\26\25\1\3\7\25\1\3\2\25\1\3\5\25\1\3"+
    "\2\0\1\25\7\0\2\3\2\0\2\3\3\0\2\3"+
    "\1\25\6\3\1\0\5\3\5\25\2\0\2\3\7\0"+
    "\3\3\5\0\213\3\65\25\22\0\4\25\5\3\12\0"+
    "\4\3\1\0\3\25\36\3\60\25\24\0\2\25\1\3"+
    "\1\25\10\3\12\0\246\3\57\25\7\0\2\3\11\0"+
    "\27\3\4\25\2\0\42\3\60\25\21\0\3\3\1\25"+
    "\13\3\12\0\46\3\53\25\15\0\1\25\7\3\12\0"+
    "\66\3\33\25\2\3\17\0\4\3\12\0\306\3\54\25"+
    "\17\0\145\3\100\25\12\0\25\3\10\25\2\3\1\25"+
    "\2\3\10\25\1\3\2\25\1\3\30\25\6\0\1\3"+
    "\2\0\2\3\4\0\1\25\1\0\1\25\2\0\14\3"+
    "\12\0\106\3\10\25\2\3\47\25\7\0\2\3\7\0"+
    "\1\25\1\3\1\25\1\0\33\3\1\25\12\0\50\25"+
    "\7\0\1\25\4\0\10\3\1\0\10\3\1\25\13\0"+
    "\56\25\20\0\3\3\1\25\42\3\71\25\7\3\11\25"+
    "\1\3\45\25\10\0\1\3\10\0\1\25\17\3\12\0"+
    "\30\3\36\25\2\3\26\0\1\3\16\0\111\3\7\25"+
    "\1\3\2\25\1\3\46\25\6\0\3\3\1\0\1\3"+
    "\2\0\1\3\7\0\1\25\1\0\10\3\12\0\6\3"+
    "\6\25\1\3\2\25\1\3\40\25\5\0\1\3\2\0"+
    "\1\3\5\0\1\25\7\3\12\0\u0136\3\23\25\4\0"+
    "\271\3\1\25\54\3\4\25\37\3\232\25\146\3\157\25"+
    "\21\3\304\25\274\3\57\25\1\3\11\0\307\3\107\25"+
    "\271\3\71\25\7\3\37\25\1\3\12\0\146\3\36\25"+
    "\2\3\5\0\13\3\60\25\7\0\11\3\4\25\14\3"+
    "\12\0\11\3\25\25\5\3\23\25\260\3\100\25\200\3"+
    "\113\25\4\3\1\0\1\25\67\0\7\3\4\0\15\25"+
    "\100\3\2\25\1\3\1\25\1\0\13\3\2\0\16\3"+
    "\370\25\10\3\326\25\52\3\11\25\367\3\37\25\61\3"+
    "\3\25\21\3\4\25\10\3\u018c\25\4\3\153\25\5\3"+
    "\15\25\3\3\11\25\7\3\12\25\3\3\2\0\1\3"+
    "\4\0\301\3\5\0\3\3\26\0\2\3\7\0\36\3"+
    "\4\0\224\3\3\0\273\3\125\25\1\3\107\25\1\3"+
    "\2\25\2\3\1\25\2\3\2\25\2\3\4\25\1\3"+
    "\14\25\1\3\1\25\1\3\7\25\1\3\101\25\1\3"+
    "\4\25\2\3\10\25\1\3\7\25\1\3\34\25\1\3"+
    "\4\25\1\3\5\25\1\3\1\25\3\3\7\25\1\3"+
    "\u0154\25\2\3\31\25\1\3\31\25\1\3\37\25\1\3"+
    "\31\25\1\3\37\25\1\3\31\25\1\3\37\25\1\3"+
    "\31\25\1\3\37\25\1\3\31\25\1\3\10\25\2\3"+
    "\151\0\4\3\62\0\10\3\1\0\16\3\1\0\26\3"+
    "\5\0\1\3\17\0\120\3\7\0\1\3\21\0\2\3"+
    "\7\0\1\3\2\0\1\3\5\0\325\3\55\25\3\3"+
    "\7\0\7\25\2\3\12\0\4\3\1\25\u0171\3\54\25"+
    "\16\0\5\3\306\25\13\3\7\0\51\3\104\25\7\0"+
    "\1\25\4\3\12\0\u0156\3\1\25\117\3\4\25\1\3"+
    "\33\25\1\3\2\25\1\3\1\25\2\3\1\25\1\3"+
    "\12\25\1\3\4\25\1\3\1\25\1\3\1\25\6\3"+
    "\1\25\4\3\1\25\1\3\1\25\1\3\1\25\1\3"+
    "\3\25\1\3\2\25\1\3\1\25\2\3\1\25\1\3"+
    "\1\25\1\3\1\25\1\3\1\25\1\3\1\25\1\3"+
    "\2\25\1\3\1\25\2\3\4\25\1\3\7\25\1\3"+
    "\4\25\1\3\4\25\1\3\1\25\1\3\12\25\1\3"+
    "\21\25\5\3\3\25\1\3\5\25\1\3\21\25\u0134\3"+
    "\12\0\6\3\336\25\42\3\65\25\13\3\336\25\2\3"+
    "\u0182\25\16\3\u0131\25\37\3\36\25\342\3\113\25\266\3"+
    "\1\0\36\3\140\0\200\3\360\0\20\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[30976];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\1\2\12\1\13\1\14\1\15\1\16"+
    "\13\4\1\17\1\20\1\21\1\22\1\23\1\1\1\24"+
    "\1\23\3\0\1\25\1\26\1\27\3\4\1\30\3\4"+
    "\1\31\7\4\2\0\1\23\2\12\1\0\2\12\1\32"+
    "\6\4\1\33\1\4\1\34\5\4\1\0\1\23\1\4"+
    "\1\35\2\4\1\36\4\4\1\37\1\40\4\4\1\41"+
    "\3\4\1\42\2\4\1\43\1\44\1\45\1\46\1\47"+
    "\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\204\0\260\0\204\0\334"+
    "\0\204\0\204\0\204\0\204\0\204\0\u0108\0\u0134\0\u0160"+
    "\0\204\0\u018c\0\204\0\u01b8\0\u01e4\0\u0210\0\u023c\0\u0268"+
    "\0\u0294\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\u039c\0\204"+
    "\0\204\0\u03c8\0\204\0\204\0\u03f4\0\u0420\0\u044c\0\u0478"+
    "\0\u04a4\0\u04d0\0\204\0\204\0\204\0\u04fc\0\u0528\0\u0554"+
    "\0\u0580\0\u05ac\0\u05d8\0\u0604\0\334\0\u0630\0\u065c\0\u0688"+
    "\0\u06b4\0\u06e0\0\u070c\0\u0738\0\u0764\0\u0790\0\u07bc\0\u07e8"+
    "\0\u0814\0\u0840\0\204\0\u086c\0\204\0\u0898\0\u08c4\0\u08f0"+
    "\0\u091c\0\u0948\0\u0974\0\334\0\u09a0\0\334\0\u09cc\0\u09f8"+
    "\0\u0a24\0\u0a50\0\u0a7c\0\u0aa8\0\u0764\0\u0ad4\0\334\0\u0b00"+
    "\0\u0b2c\0\334\0\u0b58\0\u0b84\0\u0bb0\0\u0bdc\0\334\0\334"+
    "\0\u0c08\0\u0c34\0\u0c60\0\u0c8c\0\334\0\u0cb8\0\u0ce4\0\u0d10"+
    "\0\334\0\u0d3c\0\u0d68\0\334\0\334\0\334\0\334\0\334"+
    "\0\334";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\4\1\6\1\7\1\10\1\11\1\12"+
    "\1\4\1\13\1\14\1\15\1\4\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\3\10\1\25\1\26\1\27"+
    "\1\30\1\31\1\10\1\32\5\10\1\33\1\34\1\35"+
    "\1\10\1\36\1\37\1\40\1\41\5\42\1\43\1\4"+
    "\45\42\11\44\1\45\42\44\56\0\1\5\51\0\1\10"+
    "\5\0\1\10\10\0\2\10\4\0\25\10\13\0\1\46"+
    "\4\0\1\47\52\0\1\50\10\0\1\51\42\0\1\50"+
    "\1\0\2\20\5\0\1\51\41\0\1\52\6\0\1\53"+
    "\1\54\52\0\1\55\30\0\1\10\5\0\1\10\10\0"+
    "\2\10\4\0\15\10\1\56\7\10\2\0\1\10\5\0"+
    "\1\10\10\0\2\10\4\0\2\10\1\57\22\10\2\0"+
    "\1\10\5\0\1\10\10\0\2\10\4\0\6\10\1\60"+
    "\6\10\1\61\7\10\2\0\1\10\5\0\1\10\10\0"+
    "\2\10\4\0\12\10\1\62\12\10\2\0\1\10\5\0"+
    "\1\10\10\0\2\10\4\0\12\10\1\63\2\10\1\64"+
    "\7\10\2\0\1\10\5\0\1\10\10\0\2\10\4\0"+
    "\7\10\1\65\3\10\1\66\1\67\10\10\2\0\1\10"+
    "\5\0\1\10\10\0\2\10\4\0\6\10\1\70\16\10"+
    "\2\0\1\10\5\0\1\10\10\0\2\10\4\0\24\10"+
    "\1\71\2\0\1\10\5\0\1\10\10\0\2\10\4\0"+
    "\10\10\1\72\14\10\2\0\1\10\5\0\1\10\10\0"+
    "\2\10\4\0\15\10\1\73\7\10\2\0\1\10\5\0"+
    "\1\10\10\0\2\10\4\0\10\10\1\74\14\10\2\0"+
    "\5\42\2\0\45\42\16\0\1\43\35\0\11\75\1\76"+
    "\42\75\2\47\1\44\1\47\1\77\47\47\17\0\1\100"+
    "\1\101\45\0\1\102\1\0\1\102\2\0\1\103\1\104"+
    "\47\0\1\105\37\0\1\10\5\0\1\10\10\0\2\10"+
    "\4\0\15\10\1\106\7\10\2\0\1\10\5\0\1\10"+
    "\10\0\2\10\4\0\20\10\1\107\4\10\2\0\1\10"+
    "\5\0\1\10\10\0\2\10\4\0\7\10\1\110\15\10"+
    "\2\0\1\10\5\0\1\10\10\0\2\10\4\0\22\10"+
    "\1\111\2\10\2\0\1\10\5\0\1\10\10\0\2\10"+
    "\4\0\20\10\1\112\4\10\2\0\1\10\5\0\1\10"+
    "\10\0\2\10\4\0\15\10\1\113\7\10\2\0\1\10"+
    "\5\0\1\10\10\0\2\10\4\0\17\10\1\114\5\10"+
    "\2\0\1\10\5\0\1\10\10\0\2\10\4\0\16\10"+
    "\1\115\6\10\2\0\1\10\5\0\1\10\10\0\2\10"+
    "\4\0\21\10\1\116\3\10\2\0\1\10\5\0\1\10"+
    "\10\0\2\10\4\0\21\10\1\117\3\10\2\0\1\10"+
    "\5\0\1\10\10\0\2\10\4\0\11\10\1\120\13\10"+
    "\2\0\1\10\5\0\1\10\10\0\2\10\4\0\6\10"+
    "\1\121\16\10\2\0\1\10\5\0\1\10\10\0\2\10"+
    "\4\0\11\10\1\122\13\10\2\0\1\10\5\0\1\10"+
    "\10\0\2\10\4\0\11\10\1\123\13\10\2\0\11\75"+
    "\1\124\53\75\1\124\4\75\1\125\35\75\2\0\1\44"+
    "\77\0\1\51\44\0\2\101\5\0\1\51\44\0\1\103"+
    "\1\104\52\0\2\104\33\0\1\10\5\0\1\10\10\0"+
    "\2\10\4\0\12\10\1\126\12\10\2\0\1\10\5\0"+
    "\1\10\10\0\2\10\4\0\6\10\1\127\16\10\2\0"+
    "\1\10\5\0\1\10\10\0\2\10\4\0\2\10\1\130"+
    "\22\10\2\0\1\10\5\0\1\10\10\0\2\10\4\0"+
    "\3\10\1\131\21\10\2\0\1\10\5\0\1\10\10\0"+
    "\2\10\4\0\6\10\1\132\16\10\2\0\1\10\5\0"+
    "\1\10\10\0\2\10\4\0\2\10\1\133\22\10\2\0"+
    "\1\10\5\0\1\10\10\0\2\10\4\0\15\10\1\134"+
    "\7\10\2\0\1\10\5\0\1\10\10\0\2\10\4\0"+
    "\22\10\1\135\2\10\2\0\1\10\5\0\1\10\10\0"+
    "\2\10\4\0\21\10\1\136\3\10\2\0\1\10\5\0"+
    "\1\10\10\0\2\10\4\0\14\10\1\137\10\10\2\0"+
    "\1\10\5\0\1\10\10\0\2\10\4\0\5\10\1\140"+
    "\17\10\2\0\1\10\5\0\1\10\10\0\2\10\4\0"+
    "\12\10\1\141\12\10\2\0\11\75\1\124\4\75\1\44"+
    "\35\75\1\10\5\0\1\10\10\0\2\10\4\0\6\10"+
    "\1\142\16\10\2\0\1\10\5\0\1\10\10\0\2\10"+
    "\4\0\22\10\1\143\2\10\2\0\1\10\5\0\1\10"+
    "\10\0\2\10\4\0\12\10\1\144\12\10\2\0\1\10"+
    "\5\0\1\10\10\0\2\10\4\0\21\10\1\145\3\10"+
    "\2\0\1\10\5\0\1\10\10\0\2\10\4\0\17\10"+
    "\1\146\5\10\2\0\1\10\5\0\1\10\10\0\2\10"+
    "\4\0\17\10\1\147\5\10\2\0\1\10\5\0\1\10"+
    "\10\0\2\10\4\0\4\10\1\150\20\10\2\0\1\10"+
    "\5\0\1\10\10\0\2\10\4\0\6\10\1\151\16\10"+
    "\2\0\1\10\5\0\1\10\10\0\2\10\4\0\2\10"+
    "\1\152\22\10\2\0\1\10\5\0\1\10\10\0\2\10"+
    "\4\0\12\10\1\153\12\10\2\0\1\10\5\0\1\10"+
    "\10\0\2\10\4\0\6\10\1\154\16\10\2\0\1\10"+
    "\5\0\1\10\10\0\2\10\4\0\21\10\1\155\3\10"+
    "\2\0\1\10\5\0\1\10\10\0\2\10\4\0\14\10"+
    "\1\156\10\10\2\0\1\10\5\0\1\10\10\0\2\10"+
    "\4\0\10\10\1\157\14\10\2\0\1\10\5\0\1\10"+
    "\10\0\2\10\4\0\14\10\1\160\10\10\2\0\1\10"+
    "\5\0\1\10\10\0\2\10\4\0\21\10\1\161\3\10"+
    "\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3476];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\2\11\1\1\1\11\1\1\5\11\3\1\1\11"+
    "\1\1\1\11\14\1\2\11\1\1\2\11\3\1\3\0"+
    "\3\11\17\1\2\0\3\1\1\0\1\11\1\1\1\11"+
    "\16\1\1\0\35\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[113];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public StringBuffer string = new StringBuffer();
        public static HashMap<Integer, String> stringTable = new HashMap<>();
        private static HashMap<String, Integer> symbolTable = new HashMap<>();
        private int idCounter = 0;
        public int errorLine ,errorColumn;
        private Symbol symbol(int type) {
            return new Symbol(type, yyline, yycolumn);
        }
        private Symbol symbol(int type, Object value) {
            return new Symbol(type, yyline, yycolumn, value);
        }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
            switch (zzLexicalState) {
            case STRING: {
              throw new Error("Terminatore stringa mancante a riga "+errorLine+" e colonna "+errorColumn);
            }  // fall though
            case 114: break;
            case COMMENT: {
              throw new Error("Terminatore commento mancante a riga "+errorLine+" e colonna "+errorColumn);
            }  // fall though
            case 115: break;
            default:
          { return new java_cup.runtime.Symbol(Token.EOF); }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return symbol(Token.ERROR, yytext());
            }
            // fall through
          case 41: break;
          case 2:
            { /* ignore */
            }
            // fall through
          case 42: break;
          case 3:
            { errorLine=yyline+1;errorColumn=yycolumn+1; string.setLength(0); yybegin(STRING);
            }
            // fall through
          case 43: break;
          case 4:
            { if(symbolTable.containsKey(yytext())){
                return stringTable.containsKey(symbolTable.get(yytext())) ? symbol(Token.ID, symbolTable.get(yytext())) : null;
              }
              else{
                  idCounter++;
                  stringTable.put(idCounter,yytext());
                  symbolTable.put(yytext(),idCounter);
                  return symbol(Token.ID,Integer.valueOf(String.valueOf(idCounter)));
          }
            }
            // fall through
          case 44: break;
          case 5:
            { return symbol(Token.LPAR);
            }
            // fall through
          case 45: break;
          case 6:
            { return symbol(Token.RPAR);
            }
            // fall through
          case 46: break;
          case 7:
            { return symbol(Token.ADD);
            }
            // fall through
          case 47: break;
          case 8:
            { return symbol(Token.COMMA);
            }
            // fall through
          case 48: break;
          case 9:
            { return symbol(Token.SUBTRACT);
            }
            // fall through
          case 49: break;
          case 10:
            { return symbol(Token.UNSIGNED_NUMBER, yytext());
            }
            // fall through
          case 50: break;
          case 11:
            { return symbol(Token.SEMI);
            }
            // fall through
          case 51: break;
          case 12:
            { return symbol(Token.LT);
            }
            // fall through
          case 52: break;
          case 13:
            { return symbol(Token.EQ);
            }
            // fall through
          case 53: break;
          case 14:
            { return symbol(Token.GT);
            }
            // fall through
          case 54: break;
          case 15:
            { return symbol(Token.LBRACK);
            }
            // fall through
          case 55: break;
          case 16:
            { return symbol(Token.RBRACK);
            }
            // fall through
          case 56: break;
          case 17:
            { string.append( yytext() ); return symbol(Token.STRING, yytext());
            }
            // fall through
          case 57: break;
          case 18:
            { yybegin(YYINITIAL);
            }
            // fall through
          case 58: break;
          case 19:
            { 
            }
            // fall through
          case 59: break;
          case 20:
            { yybegin(COMMENT);errorLine=yyline+1;errorColumn=yycolumn+1;
            }
            // fall through
          case 60: break;
          case 21:
            { return symbol(Token.LE);
            }
            // fall through
          case 61: break;
          case 22:
            { return symbol(Token.NE);
            }
            // fall through
          case 62: break;
          case 23:
            { return symbol(Token.GE);
            }
            // fall through
          case 63: break;
          case 24:
            { return symbol(Token.DO);
            }
            // fall through
          case 64: break;
          case 25:
            { return symbol(Token.IF);
            }
            // fall through
          case 65: break;
          case 26:
            { return symbol(Token.ASSIGN);
            }
            // fall through
          case 66: break;
          case 27:
            { return symbol(Token.FOR);
            }
            // fall through
          case 67: break;
          case 28:
            { return symbol(Token.INT);
            }
            // fall through
          case 68: break;
          case 29:
            { return symbol(Token.CASE);
            }
            // fall through
          case 69: break;
          case 30:
            { return symbol(Token.ELSE);
            }
            // fall through
          case 70: break;
          case 31:
            { return symbol(Token.THEN);
            }
            // fall through
          case 71: break;
          case 32:
            { return symbol(Token.VOID);
            }
            // fall through
          case 72: break;
          case 33:
            { return symbol(Token.FLOAT);
            }
            // fall through
          case 73: break;
          case 34:
            { return symbol(Token.WHILE);
            }
            // fall through
          case 74: break;
          case 35:
            { return symbol(Token.DOUBLE);
            }
            // fall through
          case 75: break;
          case 36:
            { return symbol(Token.IMPORT);
            }
            // fall through
          case 76: break;
          case 37:
            { return symbol(Token.RETURN);
            }
            // fall through
          case 77: break;
          case 38:
            { return symbol(Token.SWITCH);
            }
            // fall through
          case 78: break;
          case 39:
            { return symbol(Token.BOOLEAN);
            }
            // fall through
          case 79: break;
          case 40:
            { return symbol(Token.DEFAULT);
            }
            // fall through
          case 80: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Converts an int token code into the name of the
   * token by reflection on the cup symbol class/interface Token
   */
  private static String getTokenName(int token) {
    try {
      java.lang.reflect.Field [] classFields = Token.class.getFields();
      for (int i = 0; i < classFields.length; i++) {
        if (classFields[i].getInt(null) == token) {
          return classFields[i].getName();
        }
      }
    } catch (Exception e) {
      e.printStackTrace(System.err);
    }

    return "UNKNOWN TOKEN";
  }

  /**
   * Same as next_token but also prints the token to standard out
   * for debugging.
   */
  public java_cup.runtime.Symbol debug_next_token() throws java.io.IOException {
    java_cup.runtime.Symbol s = next_token();
    System.out.println( "line:" + (yyline+1) + " col:" + (yycolumn+1) + " --"+ yytext() + "--" + getTokenName(s.sym) + "--");
    return s;
  }

  /**
   * Runs the scanner on input files.
   *
   * This main method is the debugging routine for the scanner.
   * It prints debugging information about each returned token to
   * System.out until the end of file is reached, or an error occured.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java Lexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        Lexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new Lexer(reader);
          while ( !scanner.zzAtEOF ) scanner.debug_next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
