package esercitazione4;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface Token {
  /* terminals */
  public static final int EOF = -1;
  public static final int ERROR = 1;

  public static final int MAIN = 2;
  public static final int SEMI = 3;
  public static final int COMMA = 4;
  public static final int PIPE = 5;
  public static final int VAR = 6;
  public static final int INT = 7;
  public static final int FLOAT = 8;
  public static final int STRING = 9;
  public static final int BOOL = 10;
  public static final int CHAR = 11;
  public static final int VOID = 12;

  public static final int DEF = 13;
  public static final int OUT = 14;
  public static final int FOR = 15;
  public static final int IF = 16;
  public static final int ELSE = 17;
  public static final int WHILE = 18;
  public static final int TO = 19;
  public static final int LOOP = 20;
  public static final int READ = 21;
  public static final int WRITE = 22;
  public static final int WRITELN = 23;

  public static final int LPAR = 24;
  public static final int RPAR = 25;
  public static final int LBRAC = 26;
  public static final int RBRAC = 27;
  public static final int COLON = 28;
  public static final int ASSIGN = 29;
  public static final int RETURN = 30;

  public static final int TRUE = 31;
  public static final int FALSE = 32;
  public static final int PLUS = 33;

  public static final int MINUS = 34;
  public static final int TIMES = 35;
  public static final int DIV = 36;
  public static final int POW = 37;
  public static final int STR_CONCAT = 38;
  public static final int EQ = 39;
  public static final int NE = 40;
  public static final int LT = 41;
  public static final int LE = 42;
  public static final int GT = 43;
  public static final int GE = 44;
  public static final int AND = 45;
  public static final int OR = 46;
  public static final int NOT = 47;
  public static final int INTEGER_CONST = 48;
  public static final int ID = 49;
  public static final int REAL_CONST = 51;
  public static final int STRING_CONST = 52;
  public static final int CHAR_CONST = 53;

  public static final int REAL = 54;

  public static final int REF_ID = 55;
}

