
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package esercitazione5Cup;

/** CUP generated interface containing symbol constants. */
public interface Token {
  /* terminals */
  public static final int CHAR_CONST = 51;
  public static final int POW = 26;
  public static final int CHAR = 52;
  public static final int GE = 32;
  public static final int UMINUS = 27;
  public static final int INTEGER = 46;
  public static final int INTEGER_CONST = 45;
  public static final int SEMI = 3;
  public static final int OUT = 11;
  public static final int FOR = 42;
  public static final int MINUS = 23;
  public static final int WRITE = 15;
  public static final int NOT = 37;
  public static final int AND = 30;
  public static final int LT = 33;
  public static final int RPAR = 19;
  public static final int OR = 29;
  public static final int BOOL = 5;
  public static final int COMMA = 6;
  public static final int DIV = 25;
  public static final int LOOP = 44;
  public static final int PLUS = 22;
  public static final int IF = 38;
  public static final int ASSIGN = 7;
  public static final int MAIN = 2;
  public static final int WRITELN = 16;
  public static final int ID = 17;
  public static final int LE = 34;
  public static final int EOF = 0;
  public static final int RETURN = 13;
  public static final int TRUE = 53;
  public static final int error = 1;
  public static final int PIPE = 10;
  public static final int VOID = 12;
  public static final int EQ = 35;
  public static final int LBRACK = 20;
  public static final int TIMES = 24;
  public static final int COLON = 9;
  public static final int ELSE = 40;
  public static final int READ = 14;
  public static final int RBRACK = 21;
  public static final int TO = 43;
  public static final int WHILE = 41;
  public static final int FLOAT = 48;
  public static final int STR_CONCAT = 28;
  public static final int REAL_CONST = 47;
  public static final int THEN = 39;
  public static final int NE = 36;
  public static final int STRING = 50;
  public static final int LPAR = 18;
  public static final int DEF = 8;
  public static final int FALSE = 54;
  public static final int STRING_CONST = 49;
  public static final int GT = 31;
  public static final int VAR = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAIN",
  "SEMI",
  "VAR",
  "BOOL",
  "COMMA",
  "ASSIGN",
  "DEF",
  "COLON",
  "PIPE",
  "OUT",
  "VOID",
  "RETURN",
  "READ",
  "WRITE",
  "WRITELN",
  "ID",
  "LPAR",
  "RPAR",
  "LBRACK",
  "RBRACK",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POW",
  "UMINUS",
  "STR_CONCAT",
  "OR",
  "AND",
  "GT",
  "GE",
  "LT",
  "LE",
  "EQ",
  "NE",
  "NOT",
  "IF",
  "THEN",
  "ELSE",
  "WHILE",
  "FOR",
  "TO",
  "LOOP",
  "INTEGER_CONST",
  "INTEGER",
  "REAL_CONST",
  "FLOAT",
  "STRING_CONST",
  "STRING",
  "CHAR_CONST",
  "CHAR",
  "TRUE",
  "FALSE"
  };
}

